name: Check-in

on:
  pull_request:
    branches:
      - main

jobs:
  formatting-check:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - include
          - src
          - tests
    steps:
      - uses: actions/checkout@v4
      - name: Clang Formatter
        uses: jidicula/clang-format-action@v4.14.0 
        with:
          clang-format-version: '19'
          check-path: ${{ matrix.path }}
